#!/bin/sh

china_dns_server="$(uci -q get "homeproxy.config.china_dns_server")"
if echo "$china_dns_server" | grep -q ","; then
	uci -q delete "homeproxy.config.china_dns_server"
	for dns in ${china_dns_server//,/ }; do
		uci -q add_list "homeproxy.config.china_dns_server"="$dns"
	done
fi
[ -z "$(uci -q changes "homeproxy")" ] || uci -q commit "homeproxy"

exit 0
